# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Pi Rack (U6143) OLED Display
version: "dev"
slug: u6143_ssd1306
description: This is a add-on wrapper for the UCTRONICS U6143_ssd1306 Pi Rack OLED display driver
url: "https://github.com/darkgrue/addon-u6143_ssd1306"
arch:
  - armv7
startup: system
host_network: true
devices:
  - /dev/i2c-1
init: false
